name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-action:
    name: Run action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci 
      
      - name: Install ncc
        run: npm i -g @vercel/ncc

      - name: Build
        run: npm run build

      - name: Run my action
        uses: ./
        with:
          action: test_case
          env:
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN_TRELLO }}
            TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
            TRELLO_API_TOKEN: ${{ secrets.TRELLO_API_TOKEN }}
            TRELLO_BOARD_ID: '62f0e71d79853664ed62012d'
            # List "In progress"
            TRELLO_SOURCE_LIST_ID: '62f0e71d79853664ed620138'
            # List "Needs review"
            TRELLO_TARGET_LIST_ID: '63ceb47c53abdd03bea30b9c'

